### ISSUE TITLE
Getting certificate error while running auto discovery script on windows 

### ISSUE THREAD

**Issue by akashsarpate** [device42/Device42-AutoDiscovery-Scripts#11]
I am trying to run  and getting following error:  

D:\IronPython-2.7.7-win\IronPython-2.7.7>ipy64.exe api-sample.py

<urlopen error [Errno errors while validating certificate chain: ] RemoteCertificateNameMismatch, RemoteCertificateChainErrors>
---REQUEST--- https://100.18.xx.xx/api/ip/

This is on windows platform 64 bit.

**Comment by akashsarpate** [comment]
{'Content-type': 'application/x-www-form-urlencoded', 'Authorization': 'Basic YWRtaW46YWRtIW5kNDI='}cpucount=4&osverno=6.2.9200&name=servername&os=Microsoft+Windows+Server+2012+Standard&osver=None&manufacturer=vmware&memory=45312&osserial=00184-30000-00001-AA420&cpucore=4&osmanufacturer=Microsoft+Corporation&cpupower=2197

**Comment by akashsarpate** [comment]
---RESPONSE---
<urlopen error [Errno errors while validating certificate chain: ] RemoteCertificateNameMismatch, RemoteCertificateChainErrors>
---REQUEST--- https://10.81.11.148/api/ip/

**Comment by tolyadouble** [comment]
Hello @akashsarpate , please try to add this at the top of the python file : 
```
from System.Net import ServicePointManager
from System.Net.Security import RemoteCertificateValidationCallback
ServicePointManager.ServerCertificateValidationCallback = RemoteCertificateValidationCallback(lambda srvPoint, certificate, chain, errors: True)
```

**Comment by akashsarpate** [comment]
I have added this at the top of python file still getting same error

**Comment by akashsarpate** [comment]
# requires ironPython (http://ironpython.codeplex.com/) and
# powershell (http://support.microsoft.com/kb/968929)
##################################################
from System.Net import ServicePointManager
from System.Net.Security import RemoteCertificateValidationCallback
ServicePointManager.ServerCertificateValidationCallback = RemoteCertificateValidationCallback(lambda srvPoint, certificate, chain, errors: True)

import clr

clr.AddReference('System.Management.Automation')

from System.Management.Automation import (
    PSMethod, RunspaceInvoke
)

**Comment by tolyadouble** [comment]
Please change this line ( original number 83 ) : 
`reponse = urllib2.urlopen(req, context=ctx)`
to
`reponse = urllib2.urlopen(req, context=ssl._create_unverified_context())`

**Comment by tolyadouble** [comment]
hi @akashsarpate, how is it going? Does last solution work for you?

**Comment by akashsarpate** [comment]
Yes it worked. Thanks for help
